server:
  port: 8011

file:
  root: ./root
  work: ./root/work
  sftp: ./root/sftp
  archive: ./root/archive
integration:
  input: ./root/input
  pattern: \\*.csv


spring :
      mail :
          host : localhost
          port : 25
          username :
          password :
          protocol: smtp